var arr= [];
console.log(arr);
arr[0]=1;
arr[2]=2;
console.log(arr);
arr.push('kavya');
arr.push('aashi');
arr.unshift('ashi');
arr.unshift('sindhura');
arr.pop();
//arr.shift();
//arr.slice(2,4);
console.log(arr);
//console.log(arr.slice(2,4));
//arr.splice(0,2);
//console.log(arr.splice(0,2));

arr1=[1,2,3,4];
console.log(arr1);
console.log(arr1.concat(arr));
console.log(arr1.join("*"));